### ISSUE TITLE
docker.exe: failed to register layer: re-exec error: exit status 1: output: hard links not supported with legacy writer.

### ISSUE THREAD

**Issue by rs38** [StefanScherer/dockerfiles-windows#10]
`docker run -p 80:80 --name n1 stefanscherer/node-windows:latest`

docker : Unable to find image 'stefanscherer/node-windows:latest' locally
In Zeile:1 Zeichen:1
+ docker run -p 80:80 --name n1 stefanscherer/node-windows:latest
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to find ...latest' locally:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
latest: 
Pulling from stefanscherer/node-windows
9c7f9c7d9bc2: 
Already exists
de5064718b3f: Pulling fs layer
2d286c1a4f1c: 
Pulling fs layer
19356717adef: 
Pulling fs layer
36a06ad2056c: Pulling fs layer
8dedd37e14ab: 
Pulling fs layer
36a06ad2056c: Waiting
1c08f012b6c8: 
Pulling fs layer
8dedd37e14ab: 
Waiting
2561c5981334: Pulling fs layer
1c08f012b6c8: Waiting
2d286c1a4f1c: 
Verifying Checksum
2d286c1a4f1c: Download complete
19356717adef: 
Verifying Checksum
19356717adef: Download complete
8dedd37e14ab: 
Verifying Checksum
8dedd37e14ab: Download complete
36a06ad2056c: Verifying Checksum
36a06ad2056c: Download complete
2561c5981334: 
Verifying Checksum
2561c5981334: Download complete
1c08f012b6c8: 
Verifying Checksum
1c08f012b6c8: Download complete
de5064718b3f: 
Verifying Checksum
de5064718b3f: Download complete
C:\Program Files\Docker\docker.exe: failed to register layer: re-exec error: exit status 1: output: hard links not supported with legacy writer.
See 'C:\Program Files\Docker\docker.exe run --help'.

**Comment by friism** [comment]
@rs38 this is most likely because you're using the `-rc1` version of the Docker engine. Please update Windows and get the latest version of Docker.

Details here: https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

**Comment by rs38** [comment]
wow, this was fast!!! 
I am running Win10 in this case
`Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   675e622
 Built:        Mon Oct  3 00:20:26 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   675e622
 Built:        Mon Oct  3 00:20:26 2016
 OS/Arch:      windows/amd64`

**Comment by rs38** [comment]
doing the brand new update magic of
```
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name DockerMsftProvider -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force
restart-service docker
```
did the trick. no idea why. BTW regardless if Win10 oder Server2016

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```
