### ISSUE TITLE
Add a Linux Docker host

### ISSUE THREAD

**Issue by molnara** [StefanScherer/dockerfiles-windows#102]
Possible to setup a Linux host using this strategy?  Do I just manually copy over the certs and update daemon.json?

**Comment by StefanScherer** [comment]
In theory yes, but I only provide the PowerShell script (ok, there is now PowerShell on Linux ;-) ) and a Windows Dockerfile. 
The steps are from the Linux documentation at https://docs.docker.com/engine/security/https/

**Comment by StefanScherer** [comment]
I'm closing this question as I'm not planning to add a Linux variant for dockertls. I have started dockertls only as there is no docker-machine driver for a Windows host.
