### ISSUE TITLE
Update consul to 0.8.0

### ISSUE THREAD

**Issue by prochnowc** [StefanScherer/dockerfiles-windows#110]
Can you please update Consul version to 0.8.0-rc1 and later to 0.8.0 final when it is ready?
Versions before 0.8 use broken go which prevents using docker volumes.
Thanks.

**Comment by StefanScherer** [comment]
@prochnowc You can try the image `stefanscherer/consul-windows:0.8.0-rc1` if it works better for you.

**Comment by prochnowc** [comment]
@StefanScherer Thank you! Mapped volume for data directory now works.

**Comment by StefanScherer** [comment]
@prochnowc Thanks for testing. Building the final 0.8.0 image later on.
