### ISSUE TITLE
Docker image for Azure storage emulators

### ISSUE THREAD

**Issue by iemejia** [StefanScherer/dockerfiles-windows#129]
Your repo is excellent, thanks for sharing all this. I was wondering if it would be possible to create a docker image for the Microsoft Azure storage emulators. This will be a bless for developers writing integrations that don't use windows.
https://docs.microsoft.com/en-us/azure/storage/storage-use-emulator

**Comment by StefanScherer** [comment]
That is a nice idea. But it doesn't seem so easy as the emulator uses WIA and there is not full example for that.

**Comment by StefanScherer** [comment]
I'll close this one as I do not plan to build a image for that. I someone else want to give it a try... :-)
