### ISSUE TITLE
Windows Registry problem

### ISSUE THREAD

**Issue by StefanScherer** [StefanScherer/dockerfiles-windows#143]
Hi Stefan,
 
Today I have attempted to get the registry-windows container installed and working.  I was able to start it up, but I cannot push images to it.  I have tried many different things, the results always look similar to the output below.  I was able to attach to the running registry container and looked at the winevent logs, but did not find anything useful.  Do you have any suggestions on how I may be able to debug my issue?
 
Powershell console output (server 2)
```
The push refers to a repository [10.133.68.137:5000/myawesomeimage]
7ec736b79f0c: Retrying in 1 second
95d8bac835f3: Retrying in 1 second
5a7224111239: Retrying in 1 second
eaeb6837ba74: Retrying in 1 second
e3e35a236840: Retrying in 1 second
e6bb3b716717: Waiting
8d2aadcb2f54: Waiting
55cc5c7b4783: Skipped foreign layer
f358be10862c: Skipped foreign layer
received unexpected HTTP status: 503 Service Unavailable
```
 
Server 2 daemon.json:
```json
{
            "graph": "e:\\images",
            "insecure-registries": [ "10.133.68.137:5000" ]
}
```
 
Server 1: (10.133.68.137) registry startup command: 
```
docker run -d -p 5000:5000 --restart=always --name registry -v E:\registry:C:\registry stefanscherer/registry-windows:2.6.1
```
 
Thanks,
Nick

**Comment by StefanScherer** [comment]
I can reproduce the problem, but only in a fresh Win2016+Docker VM and only once.

```
mkdir C:\registry
docker run -d -p 5000:5000 --restart=always --name registry -v E:\registry:C:\registry stefanscherer/registry-windows:2.6.1
```

Then a docker push fails. It is - once again - the problem with the ContainerMappedDirectories. Even Golang suffers from it and will have a fix in Golang 1.9.

<img width="1440" alt="bildschirmfoto 2017-05-23 um 08 22 04" src="https://cloud.githubusercontent.com/assets/207759/26340941/81634b66-3f91-11e7-9567-b3674c62e785.png">

But, now kill the container

```
docker kill $(docker ps -qa)
docker rm registry
dir C:\registry
```

and restart a new container

```
docker run -d -p 5000:5000 --restart=always --name registry -v E:\registry:C:\registry stefanscherer/registry-windows:2.6.1
```

Now the docker push works.

Still we should recompile the registry binary with `FROM stefanscherer/golang-windows:devel` to have the fix compiled in.

**Comment by StefanScherer** [comment]
Indeed, the newly build `stefanscherer/registry-windows:2.6.1` images with golang 1.9 devel works out of the box in a new VM. The old one `stefanscherer/registry-windows:2.6.1-golang1.8` can be used to reproduce the problem.

**Comment by LionHeart7735** [comment]
Hi @StefanScherer , I experience the same issue with stefanscherer/registry-windows:2.6.2-1607 and stefanscherer/registry-windows:2.7.1-1607.
