### ISSUE TITLE
UWP image

### ISSUE THREAD

**Issue by toddpi314** [StefanScherer/dockerfiles-windows#145]
FYI, we are utilizing images based off of https://github.com/coderobin/windows-container/blob/master/windowsservercore/windows-build-uwp-461/Dockerfile to build UWP projects

**Comment by StefanScherer** [comment]
@todd
Thanks for the pointer. Great, that's very interesting.
What experience do you have using Jenkins in Docker? I see others building several similar solutions. I think it's time to start working on an official Dockerfile for https://github.com/jenkinsci/docker ;-)

**Comment by StefanScherer** [comment]
Here is another Jenkins with Docker on Windows project https://github.com/i-net-software/docker-boxes
It's great to see the progress everywhere.

**Comment by toddpi314** [comment]
Here is a Jenkins v2 host: https://github.com/coderobin/windows-container/tree/master/windowsservercore/jenkins

**Comment by bpham817** [comment]
I am new to this.
 Can anyone provide detail steps as how to setup  https://github.com/coderobin/windows-container/blob/master/windowsservercore/windows-build-uwp-461/Dockerfile to build uwp projects

**Comment by StefanScherer** [comment]
I don't know exactly. Maybe @toddpi314 wants to add an example in the README.md there?
My guess is to build the Docker image

```
docker build -t uwp https://raw.githubusercontent.com/coderobin/windows-container/master/windowsservercore/windows-build-uwp-461/Dockerfile
```

And then run msbuild with your sources mounted into a container

```
docker run -v "$(pwd):C:\code" uwp msbuild C:\code\yourproject.sln
```

But I haven't tested it.

**Comment by StefanScherer** [comment]
@hasan419 please open a new issue and provide more details about which registry you use on which platform. Then I can try to answer you.
