### ISSUE TITLE
Jenkins-Swarm-Slave Image and Home Reset

### ISSUE THREAD

**Issue by toddpi314** [StefanScherer/dockerfiles-windows#146]
This is problematic: https://github.com/StefanScherer/dockerfiles-windows/blob/master/jenkins-swarm-slave/Dockerfile#L4

In Windows, setting the `HOME` variable isn't enough, since `%USERPROFILE%` doesn't get updated. This means, Cigwin/MSYS tools will drop SSH keys and stuff in the `%USERPROFILE%`.

Possible Solutions:
- Update the `HOME` path to be `/c/users/containeradministrator`, like a traditional slave that will remain compatible with *NIX tools
- Update `%USERPROFILE%` (This is actually pretty complicated and involves registry rewrites, refreshing both PATH and ENVs, etc)

**Comment by StefanScherer** [comment]
The Jenkins Dockerfile was just a first test and I never built jenkins jobs with it. 
Using userprofile then might be a problem with the VOLUME as they only work with empty directories. Do we need a volume in a slave?

**Comment by toddpi314** [comment]
Currently for Linux based containers, Jenkins v2+ utilizes sibling containers. This means, there is a Swarm Container that runs the JAR that generally doesn't share too many important path details with the workspace. Then, when a workspace is built, the Jenkins Pipeline Task library offers a Docker api that allows each workspace to interact with the Docker Socket and submit their own containers to build within.

Windows is blocked on two fronts supporting this style of feature set:
- Windows Containers have TTY issues with the Jenkins Pipeline Docker Task
- Windows Containers don't allow Docker Socket binding to allow sibling containers (docker within docker)

The best we can do right now is build a Hybrid Jenkins Host container that both runs the Swarm Client and Provisions the same image to support building workspace dependencies (UWP, etc).

Hope that helps.

**Comment by jglick** [comment]
> when a workspace is built, the Jenkins Pipeline Task library offers a Docker api that allows each workspace to interact with the Docker Socket

As the original author of this plugin, I do not seriously expect this to ever be ported to Windows containers. The basic design should (IMO) be considered deprecated—it is just too hard to maintain. Work is ongoing (CC @ndeloof & @abayer) to make it easy to start a container using a specified image as part of your build, where the container would run the Jenkins agent (thus, must have at least a JRE) and would keep the workspace locally, not as a volume.

BTW I see that there is a Swarm container here, but I was surprised to see nothing like @alexellis’s [agent](https://github.com/alexellis/windowscontainers-jenkinsci/blob/master/agent/Dockerfile), i.e., an equivalent to [jenkinsci/jnlp-slave](https://hub.docker.com/r/jenkinsci/jnlp-slave/). Perhaps the Jenkins project needs to maintain such an image; CC @carlossg
