### ISSUE TITLE
What's the difference with what you did?

### ISSUE THREAD

**Issue by sebagomez** [StefanScherer/dockerfiles-windows#158]
I noticed you installed chcolatey making a web request and running the install script (`iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'));`), but I also noticed some people use the following: `Install-PackageProvider -Name chocolatey -Force`

Do you know the difference?

**Comment by StefanScherer** [comment]
There is a Package Provider "chocolatey" where you then can use eg. `Install-Package git` which then searches the package in all package providers (and then uses the chocolatey git package).

I'm used to `choco install` and prefer this command.

**Comment by sebagomez** [comment]
But I mean on how to install chcolatey, not how to call/use it.
I also noticed that using `Install-PackageProvider -Name chocolatey -Force` it does not stay in the PATH, so after install it that way I can't simple call `choco install` or `cinst`

**Comment by StefanScherer** [comment]
Yes that's what happened for me, too.  The idea behind these package providers is to use `Install-Package` instead of the `choco` binary I think.

So I'll keep at the download command, this is also shown at chocolatey.org installation instructions.

**Comment by sebagomez** [comment]
Good enough to me.
Thanks
