### ISSUE TITLE
17.06.0-ce binaries?

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#162]
Hi @StefanScherer do you know where we can download the binaries for 17.06.0-ce from?
Used to be able to get them from the moby repo releases page. There is nothing on the https://github.com/docker/docker-ce repo and the link on the [documentation](https://docs.docker.com/engine/installation/linux/docker-ce/binaries/#install-server-and-client-binaries-on-windows) to https://get.docker.com/builds/Windows/x86_64/docker-17.06.0-ce.zip is broken.

**Comment by StefanScherer** [comment]
Yes, you can find the Windows Docker CE binaries at https://download.docker.com/win/static/

I've also updated the chocolatey package to install [Docker CLI 17.06.0-ce](https://github.com/ahmetb/docker-chocolatey/blob/23fbe4fc6ab46af4b05f005674b1572a0fc3b5d4/tools/chocolateyInstall.ps1#L2-L3), so there is always a hint where to find binaries :-)

**Comment by pennywisdom** [comment]
Fantastic! Many thanks @StefanScherer
