### ISSUE TITLE
Question about registry

### ISSUE THREAD

**Issue by tfenster** [StefanScherer/dockerfiles-windows#177]
Hello,

I am successfully running an internal registry based on your image but would like to add TLS / HTTPS support. The easiest way from my point of view would be to add a Web Server to the image and configure some kind of reverse proxy to map incoming https requests to the registry at port 5000. Am I missing something? Is there an easier way?

Thanks in advance

**Comment by StefanScherer** [comment]
Hello @tfenster,
Oh that is awesome. I haven't tested it with TLS yet, but it should have the same configuration features like the Linux version. You can find the docs online at https://docs.docker.com/registry/

It seems you can confiure registry directly to use TLS certs:
https://docs.docker.com/registry/deploying/#get-a-certificate

Hope that helps.

**Comment by tfenster** [comment]
It never fails to amaze me how easy things can be in the Docker / Windows Container world. I had to try a bit but in the end it works exactly as documented. I've created a small PR (#178) to add the cert handling to your README, if you like my description
