### ISSUE TITLE
[Enhancement] Add support for multiple DNS names in SAN to dockertls.

### ISSUE THREAD

**Issue by estenrye** [StefanScherer/dockerfiles-windows#182]
**Use Case:**
WHEN a common DNS name exists for all managers in a swarm (e.g. manager.nonprod.blah.io)
AND each node must support communication using the following DNS name examples
        COMPUTERNAME
        COMPUTERNAME.ACTIVE_DIRECTORY_DOMAIN
        manager.nonprod.blah.io
AND each node in the swarm has DockerTLS enabled using the stefanscherer/dockertls-windows image
THEN `dockerhost -H COMPUTERNAME ps` should execute successfully
AND `dockerhost -H COMPUTERNAME.ACTIVE_DIRECTORY_DOMAIN ps` should execute successfully
AND `dockerhost -H manager.nonprod.blah.io ps` should execute successfully.

**Suggested Implementation**
Add a parameter to createCerts to supply an array of additional DNS names.
Modify the following line of createCerts to iterate over the array of additional DNS names and include them in the subjectAltName.
`"subjectAltName = " + (($ipAddresses.Split(',') | ForEach-Object { "IP:$_" }) -join ',') + ",DNS.1:$serverName" | Out-File extfile.cnf -Encoding Ascii`
Use an environment variable `$env:ALTERNATIVE_NAMES` to load the array of additional DNS names as a comma separated list.

**Comment by estenrye** [comment]
I intend to put up a pull request for this enhancement.

**Comment by StefanScherer** [comment]
@estenrye Thank you. Sounds reasonable. Seems like you also want to write a Cucumber integration test 👍 😃

**Comment by StefanScherer** [comment]
Closed with #183
