### ISSUE TITLE
Node server can't be reached

### ISSUE THREAD

**Issue by dustinboston** [StefanScherer/dockerfiles-windows#186]
I set up a basic node server and Dockerfile. When I run it, it says that it is running, however it cannot be accessed. Is there something that I need to do to make it work, such as opening a port in the container, or enabling some Docker setting?

I am using the following in my Dockerfile:

```
FROM stefanscherer/node-windows:7-nano
WORKDIR /app
COPY . /app
EXPOSE 3000
CMD ["node", "server"]
```

And my server.js file looks like this:

```js
const http = require('http');

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World\n');
});

server.listen(port, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

I then build it with

```bash
docker build --rm --no-cache -t test/nanoserver-node-test .
```

And run it like this

```bash
docker run -p 3000:3000 test/nanoserver-node-test
```

I get a "Server running at http://127.0.0.1:3000/" message that looks like everything is fine, but when I visit that URL, or http://localhost:3000, or http://0.0.0.0:3000, I just get a "This site can’t be reached". 

Any ideas?

**Comment by StefanScherer** [comment]
You have to use the container IP address or access it from another machine. Please have a look at https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/

**Comment by pennywisdom** [comment]
Its a limitation of [WinNAT](https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/). You have to use the private ip address of the container.

**Comment by dustinboston** [comment]
That worked, thanks!
