### ISSUE TITLE
Documentation, Read the Quick Start link 404

### ISSUE THREAD

**Issue by tangorri** [StefanScherer/dockerfiles-windows#210]
_Read the Quick Start: Windows Server Containers and Docker_ to get started with a first tutorial has bad url, kind of 404 on msdn <https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/manage_docker>.

I would have fixed it but not sure where you want to point to ? <https://docs.microsoft.com/virtualization/windowscontainers/manage-docker/configure-docker-daemon>

**Comment by StefanScherer** [comment]
@tangorri, yeah, that link would be fine. Please come up with a PR! 👍

**Comment by tangorri** [comment]
I have done the @ #211

**Comment by StefanScherer** [comment]
Thank you
