### ISSUE TITLE
CoreUtils problem on nanoserver

### ISSUE THREAD

**Issue by githubmui** [StefanScherer/dockerfiles-windows#214]
Hi,
I am facing the problem that e.g. coreutils (http://gnuwin32.sourceforge.net/packages/coreutils.htm) are not working within nanoserver-containers. When starting one of the utils nothing has happend and there is no error output as well?
On the other hand coreutils are working on nearly all windows platform (WinXp, Win7, Win10).

FYI: I am using Docker Community Edition Version 17.09.0-ce-win33 (13620) and most recent nanoserver.
Thx in advance for help!

**Comment by StefanScherer** [comment]
Hi,

Oh the latest binaries are 12 years old. Try to run 2 year old binaries in Linux containers could also be very challenging.😅 I guess the binaries are only 32bit. Nanoserver only supports 64bit binaries and has a reduced API.

**Comment by githubmui** [comment]
Thx for reply!
I think it's not related to 64bit because I also did a test with cygwin 64bit and the problem was still the same.
So maybe be the reduced API is the reason why it's not possible to install any kind of unix tools within Windows containers?

**Comment by StefanScherer** [comment]
Ok, you may try the NanoServerApiScan tool https://github.com/StefanScherer/dockerfiles-windows/blob/master/nanoserverapiscan/README.md to find some details. 

But wait, I remember a problem with stdout with mingw or cygwin. Maybe the tools just don‘t show any output in interactive mode.

**Comment by StefanScherer** [comment]
Do the tools work in windowsservercore docker container?

**Comment by githubmui** [comment]
In opposite to nanoserver containers windowsservercore containers are working!
But results must be piped to files because there is no stdout output at all.
So it's the way you remembered with mingw or cygwin.

Do you maybe know, how to solve this?

**Comment by StefanScherer** [comment]
@githubmui No I don't know what's the problem here. I guess you have to contact the maintainers (after 12 years) to suggest to investigate.

But, you may only need some tools that are part of busybox. I've just created #216 and pushed the images to Docker Hub. Some basic Unix tools like grep, sort, but also curl, wget, unzip, tar, gzip.

**Comment by githubmui** [comment]
Hi,
this is exactly what I was looking for.
Thx a lot for your help!

By the way: I did the tests also with Cygwin 2.9.0 (12. Sep. 2017) and (as I wrote) Cygwin was functional working on a windowsservercore container but without any output?

**Comment by StefanScherer** [comment]
Yes that‘s what I have found out. Redirect a command‘s stdout to a file works. So someone should look into cygwin codebase and look for a solution. I recommend opening an issue in their repo.
