### ISSUE TITLE
Windows Defender \device\harddiskvolumeX\...

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#235]
Hi @StefanScherer have you found a way to set an exclusion path for Windows Defender on a windows container hosts system to ignore / exclude all the container file systems that are being created (e.g \device\harddiskvolumeX\...

Running procmon I can see that MsMpEng.exe is being stressed when running containers on my build slaves with many many entries point to \device\harddiskvolumeX\... or similar. As soon as I have a few containers running windows defender consumes virtually all available CPU.
I'd prefer not to disable windows defender entirely, but if this is the recommended option then so be it, I just can't find clarification that this is what is recommended.

It would seem that windows defender inside the container has been addressed but on the host perhaps not. I would find it odd that I am the first person to experience this, but my google fu is not returning too much in the way of assistance.

Are you disabling this or managing things regarding Windows Defender at all?

**Comment by StefanScherer** [comment]
Hi @pennywisdom well I played with `Set-MpPreference -ExclusionPath ...` a little bit in the past to exclude the windowsfilter tree. But I finally disabled ( `Set-MpPreference -DisableRealtimeMonitoring $true` ) or removed Windows Defender ( `Uninstall-WindowsFeature Windows-Defender-Features` ) in my demo boxes as I want to show containers from a laptop in battery mode and so I disable everything inside the VM's that sucks my battery.

Further reading:
* https://docs.microsoft.com/de-de/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers
* https://www.thomasmaurer.ch/2016/07/how-to-disable-and-configure-windows-defender-on-windows-server-2016-using-powershell/

**Comment by pennywisdom** [comment]
thanks @StefanScherer hmm i suspected as much. think i will need to disable realtime scanning or remove as well then. Slightly disappointing as there are concerns over supply chain vulnerabilities with docker images already and this doesnt necessarily avert those fears. I guess we can use hyper-v containers but those have quite a bit of overhead over regular windows containers.
