### ISSUE TITLE
npm install error - getaddrinfo EAI_AGAIN registry.npmjs.org:443

### ISSUE THREAD

**Issue by akelle17** [StefanScherer/dockerfiles-windows#270]
Everytime I try to npm install a file I get the following error:
`getaddrinfo EAI_AGAIN registry.npmjs.org:443`

I am using stefanscherer/node-windows:8.9.3 image but have had this issue with many other images as well.

Initial npm error:
![npm-error](https://user-images.githubusercontent.com/35782969/35360892-3fbc7e68-012d-11e8-9a39-fa0eeb516b37.png)

npm logs:
![npm-error-2](https://user-images.githubusercontent.com/35782969/35360903-46b373de-012d-11e8-8454-d03c8758853b.png)

**Comment by StefanScherer** [comment]
Hi @akelle17 
Sounds like a general network problem inside Windows containers.
What's your environment? Windows 10 with Docker for Windows? Or a Windows Server 2016? Which versions, both OS and Docker or D4W?

Maybe running the script mentioned in https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting gives you more details.

**Comment by StefanScherer** [comment]
Still having problems?

**Comment by binarymist** [comment]
This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/

Simple fix is to create the file `/etc/docker/daemon.json`

and insert:

```
{
    "dns": ["10.0.0.2", "8.8.8.8"]
}
```
where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

**Comment by suryaveera1995** [comment]
This issue again coming, can you guys please tell me how to solve this, especially if this is on the AWS

**Comment by Rama001** [comment]
I can't install browser sync still this error appear.

**Comment by alifgithub** [comment]
pm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/npm failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.8.0
updated 1 package in 46.932s


any have idea for solve it ? help me please

**Comment by StefanScherer** [comment]
In earlier Windows versions sometimes a sleep has helped before running commands that need internet connection. It seemed that the RUN instruction and setting up network runs in parallel.

See https://github.com/StefanScherer/dockerfiles-windows/blob/967d4d80922b04170f8f1eef73fb786ce0626846/getaddrinfo/Dockerfile#L5 as an example

**Comment by luckyyang** [comment]
`/etc/docker/daemon.json` do not work for me. I have to reboot my ubuntu server to resolve my problem.

**Comment by raghureddycloud** [comment]
Restarting system resolved my issue.

**Comment by karanvij-ai** [comment]
Hi All,

I am running Docker Toolbox on windows 10 home. 

Following were the steps(In Docker console -> Docker Quick Start and using bash from git installation): 

1. npm install -g create-react-app
2. create-react-app frontend
3. cd frontend
4. npm run test
5. npm run build
6.npm run start
7. code .

Created docker file(Dockerfile.dev):
----------------------------------------------------------------------
FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]
----------------------------------------------------------------------------


$ docker build -f Dockerfile.dev .

**Output in console:** 

Sending build context to Docker daemon  146.5MB
Step 1/6 : FROM node:alpine
 ---> ef7d474eab14
Step 2/6 : WORKDIR '/app'
 ---> Using cache
 ---> c47b0eb2c3c1
Step 3/6 : COPY package.json .
 ---> Using cache
 ---> e5c66b740c8b
Step 4/6 : RUN npm install
 ---> Running in 962746bea142
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/react failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-21T01_00_35_350Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1 
-----------------------------------------------------------------


Also, I couldn't find the complete log, not sure where is location.

Please help, Thanks

**Comment by nirajkvinit** [comment]
> This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
> 
> Simple fix is to create the file `/etc/docker/daemon.json`
> 
> and insert:
> 
> ```
> {
>     "dns": ["10.0.0.2", "8.8.8.8"]
> }
> ```
> 
> where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

Yes! It worked! Thank you!

**Comment by sid42** [comment]
@karanvij-ai Seeing the same issue, were you able to find a fix?

**Comment by Tokenyet** [comment]
I got a server network issue, and a client restart to let me ssh, and the problem happened. I'll show my steps to slove this issue, hope it help someone 😄 

1. Follow the dns modification step above.
2. `sudo service docker restart` or `sudo systemctl restart docker` to restart docker.
3. sloved (only for me?).

**Comment by gitaumoses4** [comment]
@Tokenyet it did solve my issue. Thanks alot.

**Comment by edvegas** [comment]
I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.:
`docker build . --network host -t mytag ...`

**Comment by cyansprite** [comment]
Not sure if this will help or even why this is a thing but..
To fix this issue I created the `/etc/docker/daemon.json` file, `sudo systemctl restart docker`, then delete the file, `sudo systemctl restart docker` again.. THEN it works, just restarting docker didn't work, nor did it work when the file was present. Weird but.. this is here if it helps anyone.

**Comment by hmoralesp** [comment]
> I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.:
> `docker build . --network host -t mytag ...`

it's works

**Comment by anuragarwalkar** [comment]
> I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.:
> `docker build . --network host -t mytag ...`

worked for me 😊

**Comment by Xuezenghuigithub** [comment]
> I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.:
> `docker build . --network host -t mytag ...`

it's works. thank u so much~👏

**Comment by ahmeed83** [comment]
didn't work for me

`➜  test-react-app git:(master) ✗ docker build . --network host -t test-react
Sending build context to Docker daemon  823.3kB
Step 1/6 : FROM node:13.12.0-alpine
 ---> 483343d6c5f5
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> 4539c5ec716d
Step 3/6 : ADD . /app
 ---> Using cache
 ---> 376a835d8085
Step 4/6 : RUN npm install
 ---> Running in 3f86ff2a6ffb
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/@testing-library%2freact failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-06T20_31_19_172Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1`

**Comment by mojtaba-eshghie** [comment]
> This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
> 
> Simple fix is to create the file `/etc/docker/daemon.json`
> 
> and insert:
> 
> ```
> {
>     "dns": ["10.0.0.2", "8.8.8.8"]
> }
> ```
> 
> where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

Worked for me.

**Comment by DaniVS** [comment]
> I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.:
> `docker build . --network host -t mytag ...`

This solved my issue on Fedora 32.

**Comment by Kif11** [comment]
I had the same issue on WSL2 Ubuntu, @binarymist solution worked.

**Comment by mojtabaRKS** [comment]
@binarymist @Tokenyet thank you guys ! your solution was really helpful !

**Comment by d27o** [comment]
@edvegas Thx, for u solution! Its work for WSL2 Ubuntu 20.04

**Comment by CimeM** [comment]
I am using Docker for Desktop (20.10.2) on Windows 10 (20H2 OSS build 19042). I could not install NPM packages due to: 
``` npm ERR! request to https://registry.npmjs.org/canvas failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org```
Pinging the registry.npmjs.org returned that the address could not be resolved so I turned to DNS. 
Being inside a windows container I  checked what interface number the container was using with: 
```Get-DnsClient```
Then I changed to a known DNS address with: (The interface number was 4 with my container)
```Set-DnsClientServerAddress -InterfaceIndex 4 -ServerAddresses ("8.8.8.8")```

I hope this is helpful to those using windows containers on Windows clients.

**Comment by schulzalbrecht** [comment]
> This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
> 
> Simple fix is to create the file `/etc/docker/daemon.json`
> 
> and insert:
> 
> ```
> {
>     "dns": ["10.0.0.2", "8.8.8.8"]
> }
> ```
> 
> where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

that doesn't work for me and the other solutions don't work either

**Comment by NickKelly1** [comment]
restarting worked for me (`sudo systemctl restart docker`)

**Comment by preetsindhal** [comment]
> This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
> 
> Simple fix is to create the file `/etc/docker/daemon.json`
> 
> and insert:
> 
> ```
> {
>     "dns": ["10.0.0.2", "8.8.8.8"]
> }
> ```
> 
> where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

After creating the file I had to reboot the machine then it worked. 👍

**Comment by Iman** [comment]
> This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
> 
> Simple fix is to create the file `/etc/docker/daemon.json`
> 
> and insert:
> 
> ```
> {
>     "dns": ["10.0.0.2", "8.8.8.8"]
> }
> ```
> 
> where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

Works like a charm on a Digitalocean VPS

**Comment by chibuikesebastine** [comment]
> I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.: `docker build . --network host -t mytag ...`

You just saved me severally days of headache.

**Comment by mr-zero-03** [comment]
> I couldn't resolve issue with adding DNS setting to docker daemon, but I found another solution (maybe this will be useful for someone) - just use host network to resolve dns names by adding `--network host` setting, ex.: `docker build . --network host -t mytag ...`

This one worked for me! Thank you

**Comment by ShinJustinHolly3317** [comment]
> This known issue for Docker and is discussed in detail here: https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
> 
> Simple fix is to create the file `/etc/docker/daemon.json`
> 
> and insert:
> 
> ```
> {
>     "dns": ["10.0.0.2", "8.8.8.8"]
> }
> ```
> 
> where `10.0.0.2` is the first DNS server your machine requests records from, and `8.8.8.8` is the fallback DNS server, google in this case.

This works for me. Thanks a lot dude.

**Comment by ThangalakshmiKP** [comment]
> This issue again coming, can you guys please tell me how to solve this, especially if this is on the AWS

yes i am getting error like 
{
    "status": "failure",
    "err_msg": "getaddrinfo EAI_AGAIN dimaag.s3.amazonaws.com dimaag.s3.amazonaws.com:443",
    "status_code": 404
}
please help me.

**Comment by ThangalakshmiKP** [comment]
> This issue again coming, can you guys please tell me how to solve this, especially if this is on the AWS

yes i am also getting same like:
{
    "status": "failure",
    "err_msg": "getaddrinfo EAI_AGAIN dimaag.s3.amazonaws.com dimaag.s3.amazonaws.com:443",
    "status_code": 404
}
please help!

**Comment by mustafaStakater** [comment]
For the peeps using Buildah who came across this issue when using alpine image, I updated the buildah build command to override container dns with google dns server  `buildah bud --dns='8.8.8.8'`

**Comment by stasfainberg** [comment]
hey guys,

i run Docker 24.0.7 on Ubuntu 22.04.3 LTS.
i tried installing express module on a Node.js container (docker run -v $PWD:/app -w /app node npm install express) but it failed with the same errors.

weird but... **a restart solved my problem too.**
could be related to any port mapping i run before that with Nginx container (docker run -p 8080:80 -v $PWD:/usr/share/nginx/html nginx) i saw it created a FW rule on my Ubuntu 

![docker-node-error-01](https://github.com/StefanScherer/dockerfiles-windows/assets/16279799/6045ecc6-4208-4697-a56a-d1dd7ed6a1a2)

**Comment by baba216** [comment]
Hello Members,

Docker Version: 24.0.7
OS:Ubuntu 22.04.3 LTS

**Short answer**: 
even after adding dns in daemon.json its not working, enable IPv4 forwarding  [[ref](https://www.ducea.com/2006/08/01/how-to-enable-ip-forwarding-in-linux/ )] 

**Long Answer :**
Even after after adding dns in daemon.json the issue was not resolved. On further investigation and downgrading to docker version 20.10.17 , I noticed one additional error message [ie,  **IPv4 forwarding is disabled. Networking will not work**.] which was not visible for docker version 24.0.7. Please find complete details

> Step 4/6 : RUN npm install
 ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
 ---> Running in 410fdfb3445e
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/axios failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

> npm ERR! A complete log of this run can be found in:

> npm ERR!     /root/.npm/_logs/2023-12-20T09_56_37_800Z-debug.log

> The command '/bin/sh -c npm install' returned a non-zero code: 1


After I enabled ipv4 forward. It started working.
