### ISSUE TITLE
link to how to out of date now or ..?

### ISSUE THREAD

**Issue by EMCP** [StefanScherer/dockerfiles-windows#271]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

I'm just getting started with Windows.. and wanted to verify the latest instructions are correct.  Seems one of your links is pre-dating the hyper-v Docker for Windows 10 instructions and I cannot tell if I can ignore them or not..

thank you for all the container examples

**Comment by StefanScherer** [comment]
Which link do you think is out of date? One of the README.md in this repo?

The link you have pasted here is also valid. The page for Windows 10 also refers to Docker for Windows where you can switch from Linux containers to Windows containers.

**Comment by EMCP** [comment]
Yes it was the readme.md line with

`Read the Quick Start: Windows Server Containers and Docker to get started with a first tutorial.`

**Comment by StefanScherer** [comment]
OK. The link is also still valid. If there is some old content you can open an issue there as well. Microsoft also uses GitHub and the docs pages always have an "Edit" button to open a pull-request on GitHub.

The chapter "Install Docker" on page https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#install-docker
has two links, one for Server 2016 and one for Windows 10.
Windows 10 users should follow that second link and there is the Docker for Windows installation again and not the manual installation.
