### ISSUE TITLE
MSMQ

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#28]
Hi Stefan, have you had any luck using MSMQ and related sub features in containers. My findings are that only MSMQ-DCOM can be installed inside containers. Have you tried this and / or had any more luck?

**Comment by StefanScherer** [comment]
No, I haven't used MSMQ yet. You could ask in https://github.com/Microsoft/Virtualization-Documentation repo.

**Comment by pennywisdom** [comment]
ok thanks
