### ISSUE TITLE
taskkill is missing on node images

### ISSUE THREAD

**Issue by fkorotkov** [StefanScherer/dockerfiles-windows#285]
Thank you for working on node images! It's a great help for the whole community. 

I was testing `stefanscherer/node-windows:6` image and noticed that `taskkill` command is missing inside the image. It's understandable since `node-windows` is based on a nano server but `taskkill` is crucial for some server side applications since Node doesn't allow to kill processes that easily. Everyone is using `taskkill` for that purpose.

I was wondering if it's possible to include `taskkill` in the image by default?

**Comment by StefanScherer** [comment]
Thank you. I hope we can make an official Windows node image this year ;-)

It's correct that `taskkill` isn't part in the nanoserver images. So if your application depends on it you have to use the (much bigger) windowsservercore image. I have tagged them accordingly as `stefanscherer/node-windows:6-windowsservercore` (or better with 8 for the more up-to-date LTS version).

I doubt that `taskkill` is supported to run in nanoserver.

**Comment by fkorotkov** [comment]
Got it. I created my own image based on your work. Thanks again for championing it.

For future researchers here is my simplified Dockerfile:

```
FROM microsoft/windowsservercore:1709

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV NODE_VERSION 6.13.0

RUN Invoke-WebRequest $('https://nodejs.org/dist/v{0}/node-v{0}-win-x64.zip' -f $env:NODE_VERSION) -OutFile 'node.zip' -UseBasicParsing ; \
    Expand-Archive node.zip -DestinationPath C:\ ; \
    Rename-Item -Path $('C:\node-v{0}-win-x64' -f $env:NODE_VERSION) -NewName 'C:\nodejs'

SHELL ["cmd", "/S", "/C"]

RUN setx /m PATH "%PATH%;C:\nodejs"
```
