### ISSUE TITLE
yarn missing from images

### ISSUE THREAD

**Issue by grantga** [StefanScherer/dockerfiles-windows#286]
I though yarn would be installed in this images but it doesn't seem to be. Is there a way to install or run yarn?

**Comment by StefanScherer** [comment]
See the PR https://github.com/nodejs/docker-node/pull/362 which has yarn installed as well.

**Comment by StefanScherer** [comment]
I‘ve added Yarn 1.5.1. Docker images should be available soon. Let me know how it works for you.
