### ISSUE TITLE
Pfx files

### ISSUE THREAD

**Issue by dazinator** [StefanScherer/dockerfiles-windows#325]
Hi, thanks for sharing this image.

We'd like to secure using SSL but we only have a pfx file with passphrase.
Do you think its a faesible approach to mount a .pfx file, and then provide the passphrase as a docker run argument? 

I am trying to work out - is it really necessary to extract a .crt and unencrypted private key file, if this is on windows, then should it not be enough to import the .pfx into the certificate store?

Or is it that the `registry.exe` is self hosted and requires the `.crt` and unencrypted `.key` file and therefore windows cert store doesn't come into play here?

If the latter, then we are wondering if we could still mount a .pfx file and provide passphrase as docker run argument,, and then when the container starts, it could extract the `.crt` and `.key` from the `.pfx` file using the supplied passphrase, and something like `openssl`, to the relevant directory, before starting the registry.exe. We are also wondering if we did that, could we then immediately delete the .key file after the `registry.exe` had successfully started, or is it a requirement that the `.key` file has to remain persisted to disc whilst the registry is running? Basically there is a security concern about leaving unencrypted private keys around on disk and I am trying to think of a workaround for this.. If it was only short lived that might be acceptable.

Would appreciate any insight anyone may have to offer here.

**Comment by StefanScherer** [comment]
Maybe create a converter Docker image where you can docker run it with a .pfx file and get the .key and .crt files extracted.

If you want to run a registry, then use this extracted files to run it, eg. with Docker secrets in a swarm.
Otherwise you combine the logic .pfx conversion + any app that needs .key files.

**Comment by dazinator** [comment]
Thanks for replying. I did build upon the image a bit so that I pass in a .pfx, then use openssl to extract the key file to the required directory. My concern really is what happens to the private key file after the registry is started. I don't want to leave it around on disk unprotected.
I experimented a bit - it seems after the registry is started, you can delete the private key file and the registry still works. I hope this is enough and that it doesn't copy the key file somewhere else on disk - it's hard to tell really - I am not familiar with the stack the registry runs on :-)

**Comment by dazinator** [comment]
Closing as seems more related to how to secure private keys in general when using docker and the registry.
