### ISSUE TITLE
PowerShell behind an authenticating proxy

### ISSUE THREAD

**Issue by dhirschfeld** [StefanScherer/dockerfiles-windows#328]
I had a very difficult time trying to install Posh-Git in a container because of our authenticating proxy. In case it helps others the recipe which worked was:
```powershell
$user = 'DOMAIN\username';
$secpwd = ConvertTo-Securestring -AsPlainText -Force -String $password;
$creds = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ($user, $secpwd);
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force;
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force -Proxy 'http://proxy.company.com:80' -ProxyCredential $creds;
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted;
Install-Module -Scope AllUsers -Proxy 'http://proxy.company.com:80' -ProxyCredential $creds posh-git;
```

This is for the most part standard fare when using a proxy - use the `-Proxy` and `-ProxyCredential` switches, however this didn't work and I was stumped for a long time. What I eventually figured out was that inside a container I *also* needed the below lines:
```powershell
[System.Net.WebRequest]::DefaultWebProxy = New-Object System.Net.WebProxy('proxy.company.com:80');
[System.Net.WebRequest]::DefaultWebProxy.Credentials = $creds;
```
These lines weren't required outside of the container.

I'm not sure if this was something particular to our own network setup but in case it's a general thing I thought I'd post my solution to help others.

**Comment by dhirschfeld** [comment]
This isn't directly related to your repo so feel free to close. I didn't know where else to post that someone might actually find it though.

**Comment by StefanScherer** [comment]
Thanks @dhirschfeld for sharing!
I just found https://gist.github.com/wenlock/1d806c9eb668ffaa2f64fa8692967359 which describes how to run a Docker Engine behind a proxy. Have you tried setting up your Windows Docker engine that way? Don't know if that helps.

**Comment by dhirschfeld** [comment]
I hadn't seen that, but I don't think it answers the question of how to install powershell module from *within* a Windows container - which turned out to be surprisingly difficult!

Since your repo is probably the canonical reference for Windows docker builds at least this information is now discoverable, even if this issue is closed.
