### ISSUE TITLE
npm+build-tools+git

### ISSUE THREAD

**Issue by rbodziony** [StefanScherer/dockerfiles-windows#330]
hi 
 ive got error when using your build-tools + git 

 step to recreate
 1) add to build tools 8.11 or others git (ive used last 2.17.0)
 2) then inside tun 
git clone https://github.com/FaisalUmair/udemy-downloader-gui.git
3) then cd udemy-downloader-gui
4) npm install -ddd
error 
....
npm sill install loadIdealTree
npm sill install cloneCurrentTreeToIdealTree
npm sill install loadShrinkwrap
npm sill fetchPackageMetaData error for mt-files-downloader@git+https://github.com/zeltice/node-mt-files-downloader.git#cf233010b9278a8e16dab86dbfd052414672992b Command failed: C:\git\cmd\git.EXE submodule update -q --init --recursive
npm sill fetchPackageMetaData
npm sill saveTree Udeler@1.5.0
npm sill saveTree +-- dialog
.....
npm verb stack Error: Command failed: C:\git\cmd\git.EXE submodule update -q --init --recursive
npm verb stack
npm verb stack     at ChildProcess.exithandler (child_process.js:282:12)
npm verb stack     at ChildProcess.emit (events.js:182:13)
npm verb stack     at maybeClose (internal/child_process.js:957:16)
npm verb stack     at Socket.stream.socket.on (internal/child_process.js:378:11)
npm verb stack     at Socket.emit (events.js:182:13)
npm verb stack     at Pipe._handle.close [as _onclose] (net.js:598:12)
npm verb cwd C:\udemy-downloader-gui
npm verb Windows_NT 10.0.14393
npm verb argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-ddd"
npm verb node v10.1.0
npm verb npm  v5.6.0
npm ERR! code 66
npm ERR! Command failed: C:\git\cmd\git.EXE submodule update -q --init --recursive
npm ERR!
npm verb exit [ 1, true ]

....

**Comment by StefanScherer** [comment]
Step 1 is not clear to me.
Do you run a container eg. with a volume bind mount?
I've heard of problems with volumes and Git for Windows.
Does the steps work on a Windows machine, does the git submodule command work directly on a Windows machine?
Just some questions to understand the problem better.

**Comment by rbodziony** [comment]
Hi 
 Step 1 is based on your 8.11 build tools ive created Dockerfile.git And from git windows  isssue copied run with git install but changed version to 2.17.
After build just run rest commends inside container
Yes this comands works at my windows machine but inside not

**Comment by StefanScherer** [comment]
There is an issue about git submodule https://github.com/git-for-windows/git/issues/1661 that may be related to your problem.

**Comment by rbodziony** [comment]
hi 

yes seems to be that issue but founded git which works :)

ive used this .
https://wingit.blob.core.windows.net/files/MinGit-prerelease-2.17.0.windows.1.53.g4a158e75a4-BusyBox-64-bit.zip
and npm install was ok :)

**Comment by StefanScherer** [comment]
Closing this, will be fixed in git-for-windows repo, see git-for-windows/git#1661
