### ISSUE TITLE
Unknown flag: from

### ISSUE THREAD

**Issue by noizo** [StefanScherer/dockerfiles-windows#334]
Hi.
I'm trying to build node image 8.11 from Your repo.

I have had to change
FROM microsoft/windowsservercore:**10.0.14393.1707** and add my build number.
But have a problem,
```
Step 14/17 : COPY --from=download /nodejs /nodejs
Unknown flag: from
```

**Comment by noizo** [comment]
Yep, we are using outdated docker 12.x and outdated windows 2016 10.0.14393.1607
So i believe there are no way of running Your images in this environment?

**Comment by StefanScherer** [comment]
Wow, that's feels like 10 "container years" old ;-)

You are able to run these image that are on Docker Hub, but not to build these images.
A multi-stage Dockerfile is the result of doing manual steps. I've blogged in https://stefanscherer.github.io/how-to-build-nodejs-nanoserver-image/ how to build Nanoserver image long before there was multi-stage builds.
You have to split up the Dockerfile into two Dockerfiles for each stage.
And you have to create a container from the first stage, then copy a folder back onto the host. Then the second Dockerfile can copy that into the Nanoserver image.

Maybe that helps you.

Just out of curiosity: Which Docker base images are you able to run in this environment? The latest microsoft/nanoserver:sac2016?

**Comment by desirekoum** [comment]
Hi all,  I hope someone can help out with this.
I have the correct version of docker but I am still having the same error.
Step 1/19 : FROM node:latest
 ---> a8d7efbae951
...skipped lines here...
---> 8885997c1908
Removing intermediate container a5cc9f40f55e
Step 18/19 : COPY --from=0 /usr/src/app/dist/product-configuration-tool-front .
Unknown flag: from

Here is my Docker
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

Thanks for helping

**Comment by desirekoum** [comment]
Also here is my docker image docker:stable-git
