### ISSUE TITLE
Chrome on windowsservercore?

### ISSUE THREAD

**Issue by dhirschfeld** [StefanScherer/dockerfiles-windows#354]
I'd like to automate some web testing with selenium/chromedriver/chrome using `windowsservercore` containers. It seems it should be possible to run chrome in headless mode but I'm not having any luck.

I was hoping you might have an image/dockerfile I could use but it doesn't appear so. Is this something which isn't possible with Windows Containers?

**Comment by StefanScherer** [comment]
I don‘t know if Chrome runs headless in windowsservercore. 
What is the benefit running chrome in a Windows container rather than a Linux container?

I know of demand for IE / Edge containers for Selenium tests. But for Chrome I guess there already is a Linux container image.

**Comment by dhirschfeld** [comment]
My usecase is running selenium so Edge would also work I guess? I can't see any edge containers though - do they not exist (yet)?

The reason for wanting it on Windows is because it's part of a Python interactive analytics environment, [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) running on Windows containers.

Deploying in production may well run on linux containers but adding this capability to JupyterLab allows analysts to prototype code interactively in an environment they're familiar with.

**Comment by dhirschfeld** [comment]
In the interim I've found that I can use PhantomJS but since that brings up a deprecation warning I'm still interested in a more future-proof method of running selenium on Windows Containers.

**Comment by StefanScherer** [comment]
The new Windows Server 2019 is there and with it a third new base image: mcr.microsoft.com/windows:1809

It is intended for automation workloads according to the image I've added in my blog post https://stefanscherer.github.io/docker-on-windows-server-2019/ that I have stolen from a MS Ignite talk :-)

Maybe there is some hope to install Chrome there and run some automated tests? I don't have much experience with that new base image yet.

**Comment by dhirschfeld** [comment]
I actually have to use that base image (using windows insiders) because the dreaded `re-exec error: hcsshim::ImportLayer failed` bug has struck again.

https://github.com/moby/moby/issues/37821

Essentially, that means I can't use docker for windows for my workloads because it just doesn't work... except for the workaround of using the "fat" windows image.

I've been waiting for the last 6 weeks for MS to release WS2019 for MSDN download! I'll retest with that to see if I can still repro that bug.

^^^ Since I'm using the fat images currently I'll check to see if chromedriver works...

**Comment by Miro-A** [comment]
I was able to run selenium in windows containers. This works on my development Windows 10 machine. Rigth now I am struggling to run this on Windows server core 1803 host.

```
FROM openjdk:windowsservercore-1803

WORKDIR /app

COPY ./selenium-server-standalone-3.141.59.jar ./

COPY ./chromedriver.exe ./

COPY ./ChromeSetup.exe ./

RUN .\ChromeSetup.exe /silent /install

EXPOSE 4444

CMD [ "java -jar ./selenium-server-standalone-3.141.59.jar"]
```

**Comment by StefanScherer** [comment]
@mirecad Can you share your working Dockerfile? Did it work in the windowsservercore image on Windows 10 machine?

**Comment by mirecad** [comment]
@StefanScherer Yes, windowsservercore image on Windows 10 machine. Whole dockerfile is mentioned in my [comment](https://github.com/StefanScherer/dockerfiles-windows/issues/354#issuecomment-512232202).
BTW: We were able to run this container only on Windows 10. We tried also Windows Server Core 1803 as host, but without any luck.

**Comment by amirhalatzi** [comment]
@mirecad were you able to run chrome on windowsservercore? I was able to run it using windows container, otherwise it misses APIs.
