### ISSUE TITLE
MSYS2 on nanoserver?

### ISSUE THREAD

**Issue by filipesilva** [StefanScherer/dockerfiles-windows#367]
Heya,

I've been trying to get [Bazel[(https://bazel.build/) running on a windows container. It seems to be ok enough on `windowsservercore` but not on `nanoserver`.  As far as I can tell, one of the Bazel pre-requisites, MSYS2, probably cannot run on `nanoserver`:  https://github.com/Alexpux/MSYS2-packages/issues/1493

Just wanted to ask if you had tried to get MSYS2 on nanoserver.  I've been using your images as a base for mine so I thought I'd ask.

Cheers, and keep up the good work!

**Comment by StefanScherer** [comment]
Thanks @filipesilva 
It's a longer time ago when I got in touch with Git/Msys a little bit. If I had something working it would be here in the repo :-)
Maybe the new 2019 base images might help these tools.

**Comment by StefanScherer** [comment]
@filipesilva No, still the same. I've created #409 and it's still the same behaviour. Stdout works in windows/servercore, but not in windows/nanoserver.
Wow I just read what you tried with the DLL's in the linked issue 👍

**Comment by filipesilva** [comment]
Heya @StefanScherer, thanks for having a look. Yeah I don't think MSYS2 will truly work on nanoserver in the foreseeable future. 

If you trying to work with it on servercore though, I'd like to mention that I also ran into https://github.com/docker/for-win/issues/2920 which crashes the container. We still use this workaround in our test containers (https://github.com/angular/angular/blob/master/.codefresh/fix-msys64.cmd).

**Comment by StefanScherer** [comment]
Thanks for the tips @filipesilva 
Ping @selansen ^^

**Comment by selansen** [comment]
I use msys2-base-x86_64-20181211.tar.xz . - as this distro is the latest one. I did use msys2-base-x86_64-20161025.tar.xz also and it worked too.

I noticed you used 1803 in the mentioned PR. But I use
FROM mcr.microsoft.com/windows/nanoserver:1809 . 
can you pls try 1809 and see if it works for u

**Comment by filipesilva** [comment]
@selansen I got `msys2-base-x86_64-20190524.tar.xz` from http://repo.msys2.org/distrib/x86_64/ as that seems to be the new latest version.

Then I extracted it and followed these steps:
```
D:\sandbox\random>dir
 Volume in drive D is RED-16
 Volume Serial Number is 72F8-6077

 Directory of D:\sandbox\random

29/05/2019  15:58    <DIR>          .
29/05/2019  15:58    <DIR>          ..
29/05/2019  15:59    <DIR>          msys64        
               0 File(s)              0 bytes     
               3 Dir(s)  49,902,288,896 bytes free

D:\sandbox\random>docker run -v %cd%\msys64\:C:\msys64 -it --rm mcr.microsoft.com/windows/nanoserver:1903

Microsoft Windows [Version 10.0.18362.116]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\>C:\msys64\usr\bin\ls.exe

C:\>echo %errorlevel%
-1073741511
```

It looks like the same problem I had before and listed in https://github.com/msys2/MSYS2-packages/issues/1493 (missing DLLs).

**Comment by StefanScherer** [comment]
I'm closing this, nothing I can do here :-)
