### ISSUE TITLE
Set-Culture Nano Server

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#371]
Hi @StefanScherer do you know how to change the regional settings in the nanoserver image? As its a limited subset of powershell, Set-Culture does not exist. Tried updating some settings in the registry under HKCU:\Control Panel\Internation but the changes are not being reflected when I run Get-Culture.

I'm looking to change from en-us to en-gb.

**Comment by StefanScherer** [comment]
Hi @pennywisdom why not picking the nanoserver image for the specific regional variant?
Every blogpost only shows latest, sac2016, sac2019. But there are several other tags. 
I haven‘t used them so far, so please let me know if this works for you.

**Comment by pennywisdom** [comment]
yeah, I was hoping this would work too. However, I couldn't find one with a tag for en-gb unfortunately. I am assuming it's a complete list on the docker hub page.
________________________________________

**Comment by pennywisdom** [comment]
Also, I wanted to use the dotnet images for .net core 2.2 and don't really want to support my own versions of these images.
________________________________________
