### ISSUE TITLE
Docker Repository

### ISSUE THREAD

**Issue by RobertLivermore** [StefanScherer/dockerfiles-windows#373]
### Registry.EXE fails with Internal Server Error

My guess is there is a bug in the GO **registry** service not handling POSTs of data. Never worked with GO. Not sure where to look for the logs.

Followed the direction in the readme for respository. Only differece is I mapped to a different mount point
docker run -d -p 5000:5000 --restart=always --name registry -v E:\registry:C:\registry stefanscherer/registry-windows
Set the insecure-registries.

docker tag stefanscherer/registry-windows:latest vdockerrl02.actcosys.com:5000/registry:2.7.0
The push command almost works 
docker push vdockerrl02.actcosys.com:5000/registry:2.7.0

The push refers to repository [vdockerrl02.actcosys.com:5000/registry]
9305f4d63f01: Pushed
c6e6ae447c96: Pushed
ac6378375db6: Pushed
e0351966933c: Pushed
d9d7deb23bbd: Pushed
f5c673c58dcc: Skipped foreign layer
6c357baed9f5: Skipped foreign layer
**received unexpected HTTP status: 500 Internal Server Error**

I can see directories  being created; PK501 Key files. No image content.

**Comment by StefanScherer** [comment]
I also see the problems with the 2.7.0 release. The older versions should work.

**Comment by StefanScherer** [comment]
I have rebuilt the image with v2.6.2, also with a 1809 variant. Seems to be a bug in distribution repo.
