### ISSUE TITLE
oracle instant client on nanaoserver

### ISSUE THREAD

**Issue by alokranjan1234** [StefanScherer/dockerfiles-windows#378]
I am trying to install oracle instant client 18.3 on nanoserver using a similar procedure.The website says it requires visual C++ redestributable 2013. I downloaded the and installed on windowsservercore conainer and copied the files to nanoserver similary as in your dockerfile but it still does not work . It seems there are some unresolved dependencies.Are there any other dependencies required for visual C++ redestributable? do we also need to install C++ build tools?  How can i track all the dependencies required? Can you please create a nanoserver image for oracle instant client.

**Comment by StefanScherer** [comment]
@alokranjan1234 In nanoserver the default user is `ContainerUser` which has not full access to the filesystem. You may need the `USER ContainerAdministrator` instruction in your Dockerfile (or `--user ContainerAdministrator` option of `docker run` command) to get more privileges.
