### ISSUE TITLE
stefanscherer/registry-windows:Latest

### ISSUE THREAD

**Issue by hasan419** [StefanScherer/dockerfiles-windows#387]
Hi
I create private registry with  stefanscherer/registry-windows:latest in win server 2019(1809)  and
I have problem when i pushing my images from win 10(1809) to win server 2019(1809) private registry but i get below error:

docker push ipaddress:5000/helll
The push refers to repository [192.168.7.62:5000/helll]
a473df95cad9: Layer already exists
357cbc056c45: Layer already exists
75ddd2c5f09c: Skipped foreign layer
37c182b75172: Skipped foreign layer
received unexpected HTTP status: 500 Internal Server Error

**Comment by StefanScherer** [comment]
ok, 2.6.2 works fine, not the image has a 1809 variant. The 2.6.2 is also the latest tag.

**Comment by hasan419** [comment]
after push my server no exist in my images list.
