### ISSUE TITLE
PHP Image

### ISSUE THREAD

**Issue by caleblloyd** [StefanScherer/dockerfiles-windows#39]
Thanks for the great examples.  I am trying to get a PHP image working (just basic php-cli for now, no need to serve with IIS yet).  Based off some of the examples I saw here, I came up with this:

    FROM microsoft/aspnet:4.6.2-windowsservercore-10.0.14393.576

    WORKDIR /Users/ContainerAdministrator/Downloads

    SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

    # Install PHP
    RUN $url = ('http://windows.php.net/downloads/releases/php-7.1.0-nts-Win32-VC14-x64.zip'); \
        Write-Host ('Downloading {0} ...' -f $url); \
        (New-Object System.Net.WebClient).DownloadFile($url, 'php.zip'); \
        \
        Write-Host 'Installing ...'; \
        Expand-Archive -Path php.zip -DestinationPath c:\php; \
        \
        [Environment]::SetEnvironmentVariable('PATH', $env:Path + ';C:\php', [EnvironmentVariableTarget]::Machine); \
        $env:PATH = [Environment]::GetEnvironmentVariable('PATH', [EnvironmentVariableTarget]::Machine);

    RUN Write-Host 'Verifying install ...'; \
        Write-Host '  php --version'; php --version;

Everything works until `php --version`, which fails with RC=1.  If I comment out the last line, the dockerfile builds, but when I run the container, the `php` command always fails with RC=1 and no output.

I adapted this to a powershell script to run on my Windows 10 host and it installs PHP just fine.  I wondered if you had any tips for why this might be - is there a simple configuration I've missed?  I've also asked the same question [here on msdn](https://social.msdn.microsoft.com/Forums/en-US/3c5fff19-0950-42bb-b7b6-e88f38ffff9c/php-not-working-in-docker-windows-container?forum=windowscontainers)

I'd be happy to contribute the PHP image back to this repo once I get it working!

**Comment by StefanScherer** [comment]
Thank you @caleblloyd! There is no official PHP Docker image for Windows yet. So it's a very good idea to get started here, improve it and then send a pull request to https://github.com/docker-library/php

I would suggest that you open a pull rquest here and I can give you some tips to polish it 😀

But first I'll try your first version and see why php does not output anything. My first guess is that a runtime DLL is missing.

**Comment by StefanScherer** [comment]
You can also use the pull request to test build the Docker image at each git push, by adding a `build.bat` with the `docker build -t php .` command.

**Comment by StefanScherer** [comment]
@caleblloyd A lazy edition (but probably resulting in a bigger Docker image) of a `Dockerfile` is just using Chocolatey:

```Dockerfile
FROM stefanscherer/chocolatey
RUN choco install -y php
RUN php --version
```

works fine, but as you can see in the installation it also installs the VC14 runtime DLL's:

```
$ docker build -t phpchoco .
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM stefanscherer/chocolatey
 ---> beb4fc1922c1
Step 2/3 : RUN choco install -y php
 ---> Running in 5f97977f1506
Chocolatey v0.10.3
Installing the following packages:
php
By installing you accept licenses for the packages.

KB2919442 v1.0.20160915 [Approved]
kb2919442 package files install completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The install of kb2919442 was successful.
  Software install location not explicitly set, could be in package or 
  default install location if installer.

KB2919355 v1.0.20160915 [Approved]
kb2919355 package files install completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The install of kb2919355 was successful.
  Software install location not explicitly set, could be in package or 
  default install location if installer.

vcredist2015 v14.0.24215.20160928 [Approved]
vcredist2015 package files install completed. Performing other installation steps.
Downloading vcredist2015 64 bit
  from 'https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x64.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2015\14.0.24215.20160928\vc_redist.x64.exe (14.59 MB).
Download of vc_redist.x64.exe (14.59 MB) completed.
Hashes match.
Installing vcredist2015...
vcredist2015 has been installed.
Downloading vcredist2015_x86 
  from 'https://download.microsoft.com/download/6/A/A/6AA4EDFF-645B-48C5-81CC-ED5963AEAD48/vc_redist.x86.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist2015\14.0.24215.20160928\vc_redist.x86.exe (13.79 MB).
Download of vc_redist.x86.exe (13.79 MB) completed.
Hashes match.
Installing vcredist2015_x86...
vcredist2015_x86 has been installed.
 The install of vcredist2015 was successful.
  Software installed as 'exe', install location is likely default.

php v7.1.0 [Approved]
php package files install completed. Performing other installation steps.
Downloading php 64 bit
  from 'http://windows.php.net/downloads/releases/php-7.1.0-nts-Win32-VC14-x64.zip'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\php\7.1.0\php-7.1.0-nts-Win32-VC14-x64.zip (23.21 MB).
Download of php-7.1.0-nts-Win32-VC14-x64.zip (23.21 MB) completed.
Hashes match.
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\php\7.1.0\php-7.1.0-nts-Win32-VC14-x64.zip to C:\tools\php...
C:\tools\php
PATH environment variable does not have C:\tools\php in it. Adding...
Creating default php.ini
Configuring PHP extensions directory
Please make sure you have CGI installed in IIS for local hosting
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of php was successful.
  Software installed to 'C:\tools\php'

Chocolatey installed 4/4 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
 ---> a4b4b20ae4e6
Removing intermediate container 5f97977f1506
Step 3/3 : RUN php --version
 ---> Running in 17e2a67cd2c8
PHP 7.1.0 (cli) (built: Dec  2 2016 05:24:39) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
 ---> 79e9baaf53e3
Removing intermediate container 17e2a67cd2c8
Successfully built 79e9baaf53e3
```

**Comment by caleblloyd** [comment]
Very nice, Visual C++ 2015 Redistrutable was needed.  I added using:

	# Visual C++ 2015 Redistributable
	RUN $url = ('https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe'); \
		Write-Host ('Downloading {0} ...' -f $url); \
		(New-Object System.Net.WebClient).DownloadFile($url, 'vc_redist.x64.exe'); \
		Write-Host 'Installing ...'; \
		.\vc_redist.x64.exe /install /passive /norestart; \
		Write-Host 'Complete.';

I'll work on this a little more and try to package it up with fast-cgi through IIS since most folks will want to run a PHP web server.  Should have a PR to you sometime over the weekend!

**Comment by StefanScherer** [comment]
Great! You might have a look at the [node Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/2bfff897980038eede19658047dcd4fe1afd7554/node/7.2/Dockerfile) for an example using `Invoke-WebRequest`, downloading, verifying and removing the zip file as well as the enhanced `SHELL` directive to speed up the download and ZIP extraction.
