### ISSUE TITLE
Unauthorized: authentication required

### ISSUE THREAD

**Issue by andrewkelley** [StefanScherer/dockerfiles-windows#40]
I get an unauthorized: authentication required error when trying to used node-windows:latest and build the image. Am I missing something?

**Comment by StefanScherer** [comment]
The image is available on Docker Hub with my prefix: `stefanscherer/node-windows:latest`. I hope there will be an official `node:7-windowsservercore` or something like that when there is a proper CI pipeline.

So try to adjust your `FROM` line or give me some more details what you are trying.

**Comment by StefanScherer** [comment]
I'll close this one. But feel free to comment if you still have problems pulling the image.
