### ISSUE TITLE
Access to the path is denied

### ISSUE THREAD

**Issue by douglasoliveiraadv** [StefanScherer/dockerfiles-windows#405]
When I run:

```
docker run --rm `
>>   -e SERVER_NAME=my-domain `
>>   -e IP_ADDRESSES=$ips,public-ip `
>>   -v "C:\ProgramData\docker:C:\ProgramData\docker" `
>>   -v "$env:USERPROFILE\.docker:C:\Users\ContainerAdministrator\.docker" `
>>   stefanscherer/dockertls-windows
```

I have this error:
```
mkdir : Access to the path 'C:\ProgramData\docker\certs.d' is denied.
At C:\generate-certs.ps1:17 char:7
+       mkdir $dir
+       ~~~~~~~~~~
+ CategoryInfo          : PermissionDenied: (C:\ProgramData\docker\certs.d:String) [New-Item], UnauthorizedAccessException
+ FullyQualifiedErrorId : CreateDirectoryUnauthorizedAccessError,Microsoft.PowerShell.Commands.NewItemCommand
```
And, when I run:
```
mkdir ~\.docker
docker run --rm `
>>   -e SERVER_NAME=my-domain `
>>   -e IP_ADDRESSES=$ips,public-ip `
>>   -v "$env:USERPROFILE\.docker:C:\Users\ContainerAdministrator\.docker" `
>>   stefanscherer/dockertls-windows
```
I have this output:

```
    Directory: C:\ProgramData\docker

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         4/29/2019  2:45 AM                certs.d
d-----         4/29/2019  2:45 AM                config

    Directory: C:\Users\ContainerUser

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         4/29/2019  2:45 AM                .docker

    Directory: C:\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         4/29/2019  2:45 AM                DockerSSLCARoot

=== Generating CA private password

=== Writing out private key password

=== Generating CA private key
Generating RSA private key, 4096 bit long modulus
......................++
......................................................++
e is 65537 (0x10001)

=== Generating CA public key - expires in 365 days

=== Reading in CA Private Key Password

=== Generating Server private key
server-key.pem: Permission denied
1204969060:error:02FFF00D:system library:func(4095):Permission denied:bio/bss_file.c:255:fopen('server-key.pem', 'w')
1204969060:error:20FFF002:BIO routines:CRYPTO_internal:system lib:bio/bss_file.c:257:

=== Generating Server signing request
Error opening Private Key server-key.pem
747847294:error:02FFF002:system library:func(4095):No such file or directory:bio/bss_file.c:255:fopen('server-key.pem', 'r')
747847294:error:20FFF002:BIO routines:CRYPTO_internal:system lib:bio/bss_file.c:257:
unable to load Private Key

=== Signing Server request
Out-File : Access to the path 'C:\extfile.cnf' is denied.
At C:\generate-certs.ps1:64 char:44
+ ... AltName = " + ($san -join ',') | Out-File extfile.cnf -Encoding Ascii
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Out-File], UnauthorizedAccessException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

```

How can I resolve this error?! What do I need to do?

I'm on windows server 2019, at aws-ec2.

Thankful!

**Comment by varela22** [comment]
Hi,

A colleague of mine @JGalego  helped me to figure this out.

I've had the same problem as you. For the error with the PermissionDenied: (C:\ProgramData\docker\certs.d:String) the problem is related with the lack of permissions on the host folder where you mapped this container folder. For example if you mapped the host folder "c:\user\data" to the container folder "C:\ProgramData\docker", you need to grant permissions on c:\user\data (on my case i've granted to user everyone).

For the second error, the problem is because the generate-certs.ps1 script is trying to write the temporary files on the c: drive from the container and it doesn't have permissions to do it.

On function createCerts change the script to write this temporary files on another folder.

**Comment by douglasoliveiraadv** [comment]
Thanks a lot for the help!

**Comment by m0ps** [comment]
So... as for me - PowerShell script is totally broken... I'm not a pwsh guru, but... serverCertsPath variable is missing. openssl tries to save files on drive root (c:\), where it has no permission to write. I'm wondering, why it still not fixed? @StefanScherer could you please take a look on this issue and clarify.

Thanks in advance,
Maksym

**Comment by m0ps** [comment]
The solution can be founded here: https://github.com/PowerShell/PowerShell-Docker/issues/164#issuecomment-467566059
In brief - `--user ContainerAdministrator` parameter should be added to `docker run` command.

**Comment by Ivers07** [comment]
I can confirm that --user ContainerAdministrator works.
thanks @m0ps

**Comment by bverkron** [comment]
We are running into this error when running `docker build` to create an image from a Dockerfile. The error occurs when attempting to delete a file that was added to the build with the `ADD` command. Thus, we cannot use the `--user flag` as the `docker build` command does not support it.  Additionally the [referenced thread states](https://github.com/PowerShell/PowerShell-Docker/issues/164#issuecomment-467566059) 

> however in the future we intend to fully remove administrator accounts from NanoServer.

 thus this is not a good long-term solution.

### Steps to reproduce

**1) Create file called delete_test.Dockerfile with following contents**
```
FROM mcr.microsoft.com/powershell:7.0.0-preview.5-nanoserver-1809

SHELL ["pwsh", "-command"]

# -------------
# Install MinGit
# -------------
ADD https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/MinGit-2.23.0-64-bit.zip mingit.zip
RUN Expand-Archive mingit.zip -DestinationPath c:\mingit;
RUN del mingit.zip
```
**2) Run build command** 
`docker build -t "delete_tests" -f delete_test.Dockerfile .`
