### ISSUE TITLE
Traefik can't access Docker engine

### ISSUE THREAD

**Issue by tfenster** [StefanScherer/dockerfiles-windows#410]
I am not sure when that changed but now I can no longer run the Traefik image on Server 2019 as it can't connect to the npipe. When I use your compose example, I get

```traefik_1  | time="2019-05-17T07:42:38+02:00" level=error msg="Provider connection error Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.```

Running Traefik as containeradministrator fixes the problem (I'll add a PR in a minute). Am I missing something?

Windows version: 
Windows Server 2019 (1809, build 17763.437)

Docker version:
Client: Docker Engine - Enterprise
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        c3516c43ef
 Built:             03/27/2019 18:22:15
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.8
  Git commit:       c3516c43ef
  Built:            03/27/2019 18:20:29
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by StefanScherer** [comment]
Fixed with #411
