### ISSUE TITLE
32bit Node version (ENV variable for x64/x86)

### ISSUE THREAD

**Issue by gabrielenosso** [StefanScherer/dockerfiles-windows#412]
It would be great to add an ENV variable for the Node 32/64bit version.

Right now it's fixed with 'node-v{0}-win-x64.zip'.

Would be amazing to have something like:

```
ENV NODE_VERSION 10.15.3
ENV NODE_X_VERSION x86
```
And
```
RUN Invoke-WebRequest $('https://nodejs.org/dist/v{0}/node-v{0}-win-{1}.zip' -f $env:NODE_VERSION, $env:NODE_X_VERSION) -OutFile 'node.zip' -UseBasicParsing ; \
```

It would be great to have it, would save really a lot of time to everyone who needs the 32 bit version.
I am using AWS CodeBuild and it would fit at 100% with my project.

**Comment by StefanScherer** [comment]
I'm curious, why do you need the 32bit version of Node.js? Why does the 64bit version not work for your project?

**Comment by StefanScherer** [comment]
I prefer the nanoserver image for the runtime, but there 32bit binaries can not be used.
