### ISSUE TITLE
Removal of powershell from Nanoserver containers

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#419]
Hi @StefanScherer ,
I was just wondering if you had any thoughts or info to share with regard to MS decision to remove powershell from the Nanoserver container images (and having retired the older versions that did have it) and also the new Powershell container images based on Powershell core (which doesnt yet have parity with its predecessor). I was wondering whether we should plan \ consider the MS container images as building blocks where we are using multi stage builds to utilise smaller "tools" images and we use series' of these to build our images. Moving away from the idea that we pull the large windows images that have everything to a focus on smaller more focused images. 

For example using a windows curl image to replace invoke-webrequest (or perhaps one of the new powershell images) then perhaps copying the downloaded resources to another stage that used and image that has other utilities needed for building ie .net core. 
I'm not entirely sure that the changes that MS have been making to their images is that clear (in all fairness it is very complicated with the sheer number they have to support). 

Although I understand the need and benefit of the images all being regularly updated, consumers now require to have quite complex pipelines (but not necessarily complicated) similar to your repo to keep things up to date. 

I just revisited some base jenkins build images I had authored earlier this year which were used for compliling .net core solutions and used the nanoserver tag to keep the size down and the removal of powershell from the updated nonoserver .net sdk images has rendered these obsolete now. In fact I cannot update them at all without re-authoring. Do you have any thoughts on what to do with these older images that relied on Powershell (RUN statements) where powershell isnt now available by default. If you have any examples of a multistage build using some of the newer Powershell images then that would be really great. I'm basically looking for implementation patters rather than being able to achieve this ad hoc.

Thanks, be really interested to hear your thoughts on all this (if you have the time!).

**Comment by StefanScherer** [comment]
Hi @pennywisdom,

Currently there is only a preview `mcr.microsoft.com/powershell` with several windows related tags for PowerShell 7. The tags are listed at https://hub.docker.com/_/microsoft-powershell with eg. `7.0.0-preview.1-nanoserver-1803`, `7.0.0-preview.1-nanoserver-1809`, `7.0.0-preview.1-nanoserver-1903` ...

The `mcr.microsoft.com/powershell` image is multi-arch for Linux and Windows 1903.

So, I assume there will be a PowerShell 7 image for all current Windows OS versions.
