### ISSUE TITLE
Secure and Insecure registry commands are identical?

### ISSUE THREAD

**Issue by medianick** [StefanScherer/dockerfiles-windows#431]
The commands listed for tagging or pushing to secure and insecure registries are identical -- is there meant to be a difference?

https://github.com/StefanScherer/dockerfiles-windows/blob/master/registry/README.md

**Comment by StefanScherer** [comment]
They are similar. The difference is the daemon.json for using an insecure registry. You don‘t need that for a secure connection and then docker engine uses TLS.

**Comment by medianick** [comment]
Yes, I get that the registry is configured differently for secure and insecure options to begin with; I was just noting that the commands listed for `docker tag` and `docker push` _specifically_ are actually identical (e.g., they're both `docker tag stefanscherer/registry-windows:2.6.2 192.168.254.133:5000/registry:2.6.2` for `docker tag`, whether secure or insecure), so wanted to make sure that was intended. Since it's really the same command regardless of whether the registry is secure or insecure, I think it would be clearer to list it just once, e.g., with text such as "For a secure or insecure registry, use" or just "To push to your registry, use" and then the command in question. Breaking them out as separate commands but then having them be identical could cause someone (as I did) to examine them closely to see how they are different, only to find they're not. It could be clearer.

All that said, you do tremendous work here. Many thanks!!
