### ISSUE TITLE
Consul cluster setup

### ISSUE THREAD

**Issue by jasonhue8183** [StefanScherer/dockerfiles-windows#435]
Hi,

I having problem to setup 3 consul server.Any example for stack compose?  What is the value for CONSUL_BIND_INTERFACE in this case, for linux container is eth0 , what about windows container?

 What is the value for -bind If no value provided in CONSUL_BIND_INTERFACE ?

Environment:
1 ) Docker swarm with host mode port. 
2 ) windows host with server 2016 version 1607

Thanks
Jason

**Comment by StefanScherer** [comment]
Hard to tell, I never tried a whole cluster in Windows Containers.
