### ISSUE TITLE
Docker Compose not working

### ISSUE THREAD

**Issue by thomash0815** [StefanScherer/dockerfiles-windows#455]
Hi, I'm wondering why my apps don't work using docker compose. As I had my apps running on linux containers, it worked fine.

Now I needed to switch to Windows. The apps itself are perfectly running if I start them directly with docker run -it --rm -p 4200:80 123acr.azurecr.io/frontend:4100 and similar with backend.

I replaced the __ with : for the connecting string environment variables in the compose file. Docker says me the composed app is running, inspecting the backend log looks good. But I can't reach the frontend.

Any hint what I am doing wrong?

[docker-compose - edit.txt](https://github.com/StefanScherer/dockerfiles-windows/files/6561839/docker-compose.-.edit.txt)

docker-compose -f docker-compose.yml up -d

**Comment by StefanScherer** [comment]
Well, the compose.yml looks good from what I can tell. Normally container_name isn't required, but it doesn't hurt.

Maybe try with simpler base images if container to container network works. I remember that it worked for me, but that was some years ago I think. 😅

**Comment by thomash0815** [comment]
Unfortunately, I'm not working in that project anymore. I tried another approach simply starting both containers without docker compose and that worked for the solution. So the issue can be closed I think, as I can't investigate it further.
