### ISSUE TITLE
The docker file for swarm cannot be built.

### ISSUE THREAD

**Issue by mrdotmoon** [StefanScherer/dockerfiles-windows#5]
cd : Cannot find path 'C:\go\src\github.com\docker\swarm' because it does not
exist.
At line:1 char:134
+ ... docker ; git clone https://github.com/docker/swarm ; cd swarm ; git c ...
+                                                          ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\go\src\github.com\docker\swa
   rm:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLo
   cationCommand

Start-Process : This command cannot be run due to the error: The system cannot
find the file specified.
At line:1 char:167
+ ... ut v1.2.3 ; Start-Process -FilePath godep.exe -ArgumentList go, insta ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C
   ommands.StartProcessCommand

**Comment by mrdotmoon** [comment]
Could you please kindly help have a look? Thanks:)

**Comment by mrdotmoon** [comment]
And I test the docker image swarm-windows:1.2.3-nano in your docker hub, it cannot be pulled. Error is:
.\docker.exe : failed to register layer: layer does not exist.

This issue repos both in my local TP5 machine and TP5 nano in Azure.

**Comment by StefanScherer** [comment]
@mrdotmoon Could you run `docker images` and add this to this issue to compare your base images with my setup?

**Comment by mrdotmoon** [comment]
@StefanScherer , this is the docker images result running in the Azure nano TP5 server:

> REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
> nanoserver                10.0.14300.1016     3f5112ddd185        5 weeks ago         810.2 MB
> nanoserver                latest              3f5112ddd185        5 weeks ago         810.2 MB

**Comment by mrdotmoon** [comment]
It works now:) I don't know why ..

**Comment by StefanScherer** [comment]
Was on my flight back from DockerCon. So you were faster. Glad that it works for you.
