### ISSUE TITLE
Trying to start in Client mode.

### ISSUE THREAD

**Issue by TalMcMahon** [StefanScherer/dockerfiles-windows#51]
Hi, Thanks for the build.  I am trying to use it in client mode...  I am using this:

`docker run --name=agent -h agent -it --rm -p 8300-8302:8300-8302 -p 8301:8301/udp -p 8302:8302/udp
8400:8400 -p 8500:8500 -p 8600:53/udp consul -node tal-agent  -join 10.0.4.211 -advertise 10.0.0.147`

On a whim I tried:

`docker run --name=agent -h agent -it --rm -p 8300-8302:8300-8302 -p 8301:8301/udp -p 8302:8302/udp
8400:8400 -p 8500:8500 -p 8600:53/udp consul -server=false  -node tal-agent  -join 10.0.4.211 -advertise 10.0.0.147`

but either way I get this error:
`2016/12/22 10:04:42 [ERR] consul: 'dev1consul' and 'tals_agent' are both in bootstrap mode. Only one node should be in bootstrap mode, not adding raft peer.`

Thoughts?

**Comment by StefanScherer** [comment]
Can you explain your setup a little more? Do you use multiple docker hosts?

**Comment by TalMcMahon** [comment]
I figured it out, you might want to change the docs a bit or something for the newbs like me.  Ultimately, the json you are using in the config.json is configured to be in bootstrap and server mode only.  It looks lo me like once that die is cast, there is no easy way to start consul with commands that will override it.  

It was easy enough to change the config.json  -- it was just really hard to figure out it needed to be changed.

Also, not real fond of the hard coded "agent" build into the run command, it makes it a bit confusing when you are reading the consul documentation and your wrapper makes it behave differently.

**Comment by StefanScherer** [comment]
Oh, you are right. The config.json is pretty outdated, from August 2015. 
In the meantime the official [Dockerfile](https://github.com/hashicorp/docker-consul/blob/81e8c00044cb955a7a232c91dcfcb06611e18cba/0.X/Dockerfile) also looks a little different.

If you can share your better config.json I would be happy to update it here.

**Comment by StefanScherer** [comment]
@TalMcMahon I'm updating to Consul 0.7.3 in #74 and will remove the config.json so you are more flexible.
