### ISSUE TITLE
node nano dockerfile failed with error "The filename or extension is too long"

### ISSUE THREAD

**Issue by mrdotmoon** [StefanScherer/dockerfiles-windows#6]
I tried the node nano dockerfile,

```
FROM nanoserver

COPY nodejs /windows/system32

CMD [ "node.exe" ]
```

with hyper-v container nano image, it works pretty well. But when I tried it in a windows TP5 nano server (in Azure), it failed with below error:

`msg="hcsshim::ImportLayer failed in Win32: The filename or extension is too long. (0xce) layerId=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\0cca83375d700cfdc9dfb627b4102584a767720ba4cf55339f63020fc2aa7deb flavour=1 folder=C:\\Windows\\TEMP\\hcs306829939"`

Have you tried it in nano server? Is there any difference between nano server container and hyper-v nano container?

Any help will be highly appreciated. Thanks.

**Comment by StefanScherer** [comment]
I haven't tried it in nano server yet. I'll spin up a TP5 Nano in Azure when I have some time.

You could try to COPY only the node.exe into the container and try another target directory. But that's only a guess.

**Comment by mrdotmoon** [comment]
Yes, without npm, only copy node.exe it works.

BTW, do you plan to write a nano dockerfile for mongodb?

**Comment by StefanScherer** [comment]
ok, so COPYing the npm.cmd in another line should also work. So there might be a problem copying a whole directory tree.

MongoDB in Nano sounds interesting, but I'm busy right now. But it should be not much more than adding a Dockerfile for nano like the one for [windowservercore](https://github.com/StefanScherer/dockerfiles-windows/blob/master/mongo/3.2/Dockerfile) and enhance the [build.bat](https://github.com/StefanScherer/dockerfiles-windows/blob/master/mongo/build.bat) to download and extract it with a windowsservercore container using the Dockerfile.build file and then running two docker build, one for servercore, another for the nanoserver.

**Comment by mrdotmoon** [comment]
I've tried just now fro mongodb, the offical mongod.exe crashed in Nano. Then I am using Nano API tool scan, it says lacking of a lot API in MSVCR120.dll and MSVCP120.dll, which is Visual Studio 2013 runtime files. I clone the code and rebuild by Visual Studio 2015, and It works well for Nano. Thanks:)

**Comment by StefanScherer** [comment]
This is amazing! Just recompiling with the newer VS 2015 did it? Do you want to open an issue at MongoDB so they are aware of the Nano server incompatibility?

**Comment by StefanScherer** [comment]
@mrdotmoon One other idea. What about dockerizing the build steps? Does it compile with eg. https://github.com/felixrieseberg/windows-build-tools installed?
That would be a great tutorial how to build C/C++ with only Docker installed on your host machine :-)

**Comment by mrdotmoon** [comment]
That is a good idea! I am using this instruction: https://github.com/mongodb/mongo/wiki/Build-Mongodb-From-Source#windows-specific-instructions. 

But the build cost about 1.5 hours in my dev machine (Core i7-3770, 16GB) using 1 parallel job, it may be a pain for container.

**Comment by mrdotmoon** [comment]
This long path issue has been fixed in RTM build. Thanks:)
