### ISSUE TITLE
volumes directives doesnt work

### ISSUE THREAD

**Issue by markl17** [StefanScherer/dockerfiles-windows#7]
http://stackoverflow.com/questions/38702808/docker-is-not-allowing-to-mount-a-directory-into-a-drupal-container/38709202#38709202

**Comment by StefanScherer** [comment]
This repo contains only Dockerfiles to build Windows Docker images running on Windows 2016 / Windows 10 in the Windows Containers feature. It seems that you try to run Linux containers. Please use SO or docker/docker repo for these issues.
