### ISSUE TITLE
traefik web interface :8080

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#75]
Hi Stefan,
have you been able to access the web interface for your traefik container? I am having difficulties accessing it, and continually get the err ```500 Internal Server Error```. 
Furthermore, when I check ```docker logs [container]``` nothing is being written to the access logs to help diagnose the issue. My configuration mirrors your initial commit in 202f354eb87881deae28873516fe2e6197cfdb9c
Thanks

**Comment by pennywisdom** [comment]
Interestingly, i can access the api methods without error and the data looks good that is returned.

**Comment by StefanScherer** [comment]
I also only get 500 error. I think I've compiled the binary without the assets. Manual steps are error prone ;-)

I'm adjusting `.travis.yml` to let my fork build at https://travis-ci.org/StefanScherer/traefik and push the exe to GitHub releases.
