### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#80]
Hi Stefan, firstly thanks for your awesome repo and contributions, its a fantastic resource.
I was wondering if you have any thoughts from a security perspective regarding windows containers. A couple of areas that I am thinking of are:

1) security scanning of the containers, finding vulnerabilities, locking down ports (firewall in container? or similar to iptables)
2) locking down scripting capabilities for people creating containers in an organisation. So for example, say you limit access to base containers from a known store, that are full patched and scanned and have say Java installed, but then disabling the potential to run powershell's invoke-webrequest or similar to install chocolatey then further packages etc in an uncontrolled way. I guess you could do this from a network perspective but thats somewhat unrealistic in a general development network.

Perhaps its just a case of scanning the containers and verifying against a whitelist or similar. Be really interested to hear if you have started to experiment with anything or have any thoughts on this.

**Comment by StefanScherer** [comment]
Hi Alex, 
That are really good questions. But I think the audience here is very small for such important topics.
I suggest to open an issue in https://github.com/Microsoft/Virtualization-Documentation as there are more people of the Microsoft containers team watching. A result of this may be a chapter in the official docs about security.

A Docker image is a snapshot that you can't modify, only by creating a different image from it or run it as a container and modify files at runtime.
So to be sure to have the unmodified version, just kill the container and run a new one.

What I did in a short test is run a Linux container that modify some files at runtime and check this with `docker diff`

```
$ docker run -it ubuntu bash
root@81084a5373e4:/# touch file1.txt
root@81084a5373e4:/# touch file2.txt
root@81084a5373e4:/# 
```

Now parallel in another terminal run

```
$ docker diff 8108
A /file1.txt
A /file2.txt
```

So you can monitor what has changed at runtime and eg. check if someone has change executables etc.

Unfortunately this command does not work (yet?) with Windows containers:

```
$ docker diff 5584
Error response from daemon: Windows does not support diff of a running container
```

**Comment by pennywisdom** [comment]
Thanks @StefanScherer . I wonder if there is any intention to implement something like https://github.com/docker/docker-bench-security that works in the windows world. i would imagine it needs to be completely separate as the security models etc are so different. But the model of delivery and usage is good.

**Comment by StefanScherer** [comment]
Having something similar to the dockerbench for Windows would be great. You can't run the script from inside a container as `--net host --pid host` does not work on Windows.

So it would be more like the [Debug-ContainerHost.ps1](https://github.com/Microsoft/Virtualization-Documentation/blob/live/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1) script, but for security checks.

You may open an issue in the docker-bench-security to start thinking about this with the maintainers.

**Comment by pennywisdom** [comment]
FYI I've submitted [561](https://github.com/Microsoft/Virtualization-Documentation/issues/561)

**Comment by StefanScherer** [comment]
Thanks. I'm closing this one and hope for more responses and discussion in 561 ;-)
