### ISSUE TITLE
docker-compose nat issues

### ISSUE THREAD

**Issue by pennywisdom** [StefanScherer/dockerfiles-windows#82]
Hi Stefan, sorry about the cross post, not sure if you are active on the docker/for-win repo or not (if so please feel free to close this). Have you come across issues with docker-compose as detailed [here in 514](https://github.com/docker/for-win/issues/514).

I was expecting / hoping that things would be a little more stable using  docker v1.13.1 and  compose v1.11.1, but looks like the issues with networking still exist. I am randomly getting problems when using compose to deploy where one of the services fails with an unspecified error similar to

> Cannot start service xyz: failed to create endpoint xyz_1 on network nat: HNS failed with error : Unspecified error

its quite random and a docker-compose down, then a docker-compose up often resolves it.

Be really intersted / grateful to hear if you have come across this.

**Comment by StefanScherer** [comment]
Hi Alex, the docker/for-win might be the wrong channel as it is for the D4W product for Win10 with both Linux and Windows containers.
As you are trying this on Win2016 it would be better to open an issue in either docker/compose or docker/docker.
Networking is still in progress. What's docker-compose up -p ?

**Comment by pennywisdom** [comment]
hi @StefanScherer thanks. I have transferred to [docker/compose](https://github.com/docker/compose/issues/4521).

Sorry thats a typo, should be docker-compose -d --no-build
