### ISSUE TITLE
docker: Error response from daemon

### ISSUE THREAD

**Issue by zygissd** [StefanScherer/dockerfiles-windows#86]
hello, when I use this image ,I got some exception.
I use docker command like this:
`docker run -d -p 5000:5000 --restart=always -v C:\registry:C:\registry  --name registry stefanscherer/registry-windows:2.5.1`

the container is create sucess,but when start, it throw exception:
`docker: Error response from daemon: container ec87fe5b36715a580b43e38fafe28655afc7cfd559bc1a39e77ca7dfffe21c70 encountered an error during CreateContainer: failure in a Windows system call: The system cannot find the path specified. (0x3) extra info: {"SystemType":"Container","Name":"ec87fe5b36715a580b43e38fafe28655afc7cfd559bc1a39e77ca7dfffe21c70","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{a006cf77-f9ca-11e6-8da1-d43d7ef82142}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\ec87fe5b36715a580b43e38fafe28655afc7cfd559bc1a39e77ca7dfffe21c70","Layers":[{"ID":"21082560-4910-57f6-a566-8d88fdcee239","Path":"C:\\ProgramData\\docker\\windowsfilter\\b5c801c5e0c76089f2cbbe5fd30d0920fd7f2fdfadb6aea4561f9571baffab1a"},{"ID":"d90f568e-70e3-58de-8178-99f05898ded8","Path":"C:\\ProgramData\\docker\\windowsfilter\\df9a9696464b64c302d5f0cfc11a92b61c384d23769a2193425b52f11817cf84"},{"ID":"58253145-22c0-54bf-9f8f-87a73a312653","Path":"C:\\ProgramData\\docker\\windowsfilter\\c16396cb6ec58afa829404484519a4f1d549b449486aca640f39bb00b6df9746"},{"ID":"5b061320-1dcf-5edb-b5c6-980af538f6ac","Path":"C:\\ProgramData\\docker\\windowsfilter\\359a8eddd24f82fa8129cd9e9c1078cfa756d8196be61983fd6e7869e32291f7"},{"ID":"03cd5278-b52f-5301-a32f-39e1e0806197","Path":"C:\\ProgramData\\docker\\windowsfilter\\0fb2f600e557132c684372cfdf7713218ff7cb39feab4f0edc79df89e81e2b23"}],"HostName":"ec87fe5b3671","MappedDirectories":[{"HostPath":"c:\\registry","ContainerPath":"c:\\registry","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0}],"HvPartition":false,"EndpointList":["5454e416-95ae-4dbe-b936-92cc16642c45"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.
`
I use windows server 2016 Datacenter   10.0.14393      
By the way, My OS language is Simple-Chinese

**Comment by StefanScherer** [comment]
@zygissd Please try again with the newer Docker image `stefanscherer/registry-windows:2.6.0`.
I have updated the readme on Docker Hub as well as the [`run-registry.ps1`](https://github.com/StefanScherer/docker-windows-box/blob/2c1645ced64776c5f2099c0918ab254d28a0c3fc/swarm-demo/scripts/run-registry.ps1) script.

**Comment by StefanScherer** [comment]
Closing this as it should be fixed in newer image. If you still have problems, let me know.
