### ISSUE TITLE
docker-compose subjectAltName needs DNS

### ISSUE THREAD

**Issue by molnara** [StefanScherer/dockerfiles-windows#99]
docker-compose need to have a proper subjectAltName as per the [following open issue on github](https://github.com/docker/compose/issues/3365)

For example, I setup TLS on a new vm on azure, and docker cli commands work fine, but docker-compose gives the following error:

`backports.ssl_match_hostname.CertificateError: hostname '<mydockervm>.canadaeast.cloudapp.azure.com' doesn't match either of '127.0.0.1', '10.0.0.4'`

The solution is to add proper DNS entry to subjectAltName like so:

`subjectAltName = IP:10.0.0.4,IP:127.0.0.1,DNS.1:*.cloudapp.net,DNS.2:*.*.cloudapp.azure.com`

**Comment by StefanScherer** [comment]
Thanks @molnara. I'll test it this week to work with docker-compose with an Azure machine.

**Comment by StefanScherer** [comment]
So we need another environment variable to append such DNS entries.

**Comment by StefanScherer** [comment]
See #121, I haven't added new parameters - that would add more complexity in my opinion. If you use the FQDN in the SERVER_NAME environment variable then this is also added as DNS.1 to the subjectAltName and works fine for me with docker-compose from a local machine communicating with an Azure Windows Docker engine.
